cc_library(
    name = "glad",
    srcs = ["src/glad.c"],
    hdrs = [
        "include/KHR/khrplatform.h",
        "include/glad/glad.h",
    ],
    includes = ["include"],
    visibility = ["//examples/dev:__pkg__"],
)
